### ISSUE TITLE
Allow other currencies

### ISSUE THREAD

**Issue by StijnBTC** [satoshiradio/beertap#5]
For now you can only set the price in euro's, it would be nice if you could set the price in other currencies.

**Comment by JasonRodriguez1474** [comment]
Greetings, I'm attempting to tackle this issue but after importing the requirements.txt in my venv and running main.py I'm getting the following. 

``(venv) [guatejason@power beertap]$ /home/guatejason/Documents/source-controlled-development/beertap/venv/bin/python /home/guatejason/Documents/source-controlled-development/beertap/settings.py
Traceback (most recent call last):
  File "/home/guatejason/Documents/source-controlled-development/beertap/settings.py", line 10, in <module>
    GPIO_TAP_PIN = env.int("GPIO_TAP_PIN")
  File "/home/guatejason/Documents/source-controlled-development/beertap/venv/lib64/python3.10/site-packages/environs/__init__.py", line 116, in method
    raise EnvError('Environment variable "{}" not set'.format(proxied_key or parsed_key))
environs.EnvError: Environment variable "GPIO_TAP_PIN" not set``

Any idea how to get past this? Also, once I get this working I'd also like to work on a contribution guide for this repository to make it more accessible for others to begin contributing and move past stuff like this.
